services:
  postgres:
    container_name: 'postgres_crud'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=crud-spring'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    restart: always
    ports:
      - '8905:5432'
